/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/home': RouteRecordInfo<
      '/home',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | '/home/'
      | '/home/role'
      | '/home/role/'
      | '/home/user'
      | '/home/user/'
    >,
    '/home/': RouteRecordInfo<
      '/home/',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home/role': RouteRecordInfo<
      '/home/role',
      '/home/role',
      Record<never, never>,
      Record<never, never>,
      | '/home/role/'
    >,
    '/home/role/': RouteRecordInfo<
      '/home/role/',
      '/home/role',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home/user': RouteRecordInfo<
      '/home/user',
      '/home/user',
      Record<never, never>,
      Record<never, never>,
      | '/home/user/'
    >,
    '/home/user/': RouteRecordInfo<
      '/home/user/',
      '/home/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/home.vue': {
      routes:
        | '/home'
        | '/home/'
        | '/home/role'
        | '/home/role/'
        | '/home/user'
        | '/home/user/'
      views:
        | 'default'
    }
    'src/pages/home/index.vue': {
      routes:
        | '/home/'
      views:
        | never
    }
    'src/pages/home/role.vue': {
      routes:
        | '/home/role'
        | '/home/role/'
      views:
        | 'default'
    }
    'src/pages/home/role/index.vue': {
      routes:
        | '/home/role/'
      views:
        | never
    }
    'src/pages/home/user.vue': {
      routes:
        | '/home/user'
        | '/home/user/'
      views:
        | 'default'
    }
    'src/pages/home/user/index.vue': {
      routes:
        | '/home/user/'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
