/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'home_index': RouteRecordInfo<
      'home_index',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    'home': RouteRecordInfo<
      'home',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | '/home/'
      | 'role'
      | 'role_index'
      | 'task'
      | 'task_index'
      | 'user'
      | 'user-details'
      | 'user_create'
      | 'user_index'
    >,
    '/home/': RouteRecordInfo<
      '/home/',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'role': RouteRecordInfo<
      'role',
      '/home/role',
      Record<never, never>,
      Record<never, never>,
      | 'role_index'
    >,
    'role_index': RouteRecordInfo<
      'role_index',
      '/home/role',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'task': RouteRecordInfo<
      'task',
      '/home/task',
      Record<never, never>,
      Record<never, never>,
      | 'task_index'
    >,
    'task_index': RouteRecordInfo<
      'task_index',
      '/home/task',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'user': RouteRecordInfo<
      'user',
      '/home/user',
      Record<never, never>,
      Record<never, never>,
      | 'user_index'
    >,
    'user_index': RouteRecordInfo<
      'user_index',
      '/home/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'user_create': RouteRecordInfo<
      'user_create',
      '/home/user/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'user-details': RouteRecordInfo<
      'user-details',
      '/home/user/details',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'login': RouteRecordInfo<
      'login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | 'home_index'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/home.vue': {
      routes:
        | '/home/'
        | 'home'
        | 'role'
        | 'role_index'
        | 'task'
        | 'task_index'
        | 'user'
        | 'user-details'
        | 'user_create'
        | 'user_index'
      views:
        | 'default'
    }
    'src/pages/home/index.vue': {
      routes:
        | '/home/'
      views:
        | never
    }
    'src/pages/home/role.vue': {
      routes:
        | 'role'
        | 'role_index'
      views:
        | 'default'
    }
    'src/pages/home/role/index.vue': {
      routes:
        | 'role_index'
      views:
        | never
    }
    'src/pages/home/task.vue': {
      routes:
        | 'task'
        | 'task_index'
      views:
        | 'default'
    }
    'src/pages/home/task/index.vue': {
      routes:
        | 'task_index'
      views:
        | never
    }
    'src/pages/home/user.vue': {
      routes:
        | 'user'
        | 'user_index'
      views:
        | 'default'
    }
    'src/pages/home/user/index.vue': {
      routes:
        | 'user_index'
      views:
        | never
    }
    'src/pages/home/user.create.vue': {
      routes:
        | 'user_create'
      views:
        | never
    }
    'src/pages/home/user.details.vue': {
      routes:
        | 'user-details'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | 'login'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
