/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    layout: RouteRecordInfo<'layout', '/', Record<never, never>, Record<never, never>, never>
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      never
    >
    '/cloud': RouteRecordInfo<
      '/cloud',
      '/cloud',
      Record<never, never>,
      Record<never, never>,
      | '/cloud/'
      | '/cloud/bugs/'
      | '/cloud/bugs/indexKeep'
      | '/cloud/graph/'
      | '/cloud/role/'
      | '/cloud/user'
      | '/cloud/user/'
      | '/cloud/vueKnown/'
    >
    '/cloud/': RouteRecordInfo<'/cloud/', '/cloud', Record<never, never>, Record<never, never>, never>
    '/cloud/bugs/': RouteRecordInfo<'/cloud/bugs/', '/cloud/bugs', Record<never, never>, Record<never, never>, never>
    '/cloud/bugs/indexKeep': RouteRecordInfo<
      '/cloud/bugs/indexKeep',
      '/cloud/bugs/indexKeep',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/cloud/graph/': RouteRecordInfo<'/cloud/graph/', '/cloud/graph', Record<never, never>, Record<never, never>, never>
    '/cloud/role/': RouteRecordInfo<'/cloud/role/', '/cloud/role', Record<never, never>, Record<never, never>, never>
    '/cloud/user': RouteRecordInfo<
      '/cloud/user',
      '/cloud/user',
      Record<never, never>,
      Record<never, never>,
      '/cloud/user/'
    >
    '/cloud/user/': RouteRecordInfo<'/cloud/user/', '/cloud/user', Record<never, never>, Record<never, never>, never>
    '/cloud/vueKnown/': RouteRecordInfo<
      '/cloud/vueKnown/',
      '/cloud/vueKnown',
      Record<never, never>,
      Record<never, never>,
      never
    >
    home: RouteRecordInfo<
      'home',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | '/home/'
      | '/home/dashboard'
      | '/home/dashboard/'
      | 'role'
      | 'role_index'
      | 'task'
      | 'task_index'
      | 'user'
      | 'user_create'
      | 'user_details'
      | 'user_index'
    >
    role: RouteRecordInfo<'role', '/home/role', Record<never, never>, Record<never, never>, never>
    user: RouteRecordInfo<'user', '/home/user', Record<never, never>, Record<never, never>, never>
    user_create: RouteRecordInfo<
      'user_create',
      '/home/user/create/:id?',
      { id?: ParamValueZeroOrOne<true> },
      { id?: ParamValueZeroOrOne<false> },
      never
    >
    user_details: RouteRecordInfo<
      'user_details',
      '/home/user/details/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>, never>
    '/home/dashboard': RouteRecordInfo<
      '/home/dashboard',
      '/home/dashboard',
      Record<never, never>,
      Record<never, never>,
      '/home/dashboard/'
    >
    '/home/dashboard/': RouteRecordInfo<
      '/home/dashboard/',
      '/home/dashboard',
      Record<never, never>,
      Record<never, never>,
      never
    >
    role_index: RouteRecordInfo<'role_index', '/home/role', Record<never, never>, Record<never, never>, never>
    task: RouteRecordInfo<'task', '/home/task', Record<never, never>, Record<never, never>, 'task_index'>
    task_index: RouteRecordInfo<'task_index', '/home/task', Record<never, never>, Record<never, never>, never>
    user_index: RouteRecordInfo<'user_index', '/home/user', Record<never, never>, Record<never, never>, never>
    login: RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>, never>
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: 'layout'
      views: never
    }
    'src/pages/[...path].vue': {
      routes: '/[...path]'
      views: never
    }
    'src/pages/cloud.vue': {
      routes:
        | '/cloud'
        | '/cloud/'
        | '/cloud/bugs/'
        | '/cloud/bugs/indexKeep'
        | '/cloud/graph/'
        | '/cloud/role/'
        | '/cloud/user'
        | '/cloud/user/'
        | '/cloud/vueKnown/'
      views: 'default'
    }
    'src/pages/cloud/index.vue': {
      routes: '/cloud/'
      views: never
    }
    'src/pages/cloud/bugs/index.vue': {
      routes: '/cloud/bugs/'
      views: never
    }
    'src/pages/cloud/bugs/indexKeep.vue': {
      routes: '/cloud/bugs/indexKeep'
      views: never
    }
    'src/pages/cloud/graph/index.vue': {
      routes: '/cloud/graph/'
      views: never
    }
    'src/pages/cloud/role/index.vue': {
      routes: '/cloud/role/'
      views: never
    }
    'src/pages/cloud/user.vue': {
      routes: '/cloud/user' | '/cloud/user/'
      views: 'default'
    }
    'src/pages/cloud/user/index.tsx': {
      routes: '/cloud/user/'
      views: never
    }
    'src/pages/cloud/vueKnown/index.vue': {
      routes: '/cloud/vueKnown/'
      views: never
    }
    'src/pages/home.vue': {
      routes:
        | '/home/'
        | '/home/dashboard'
        | '/home/dashboard/'
        | 'home'
        | 'role'
        | 'role_index'
        | 'task'
        | 'task_index'
        | 'user'
        | 'user_create'
        | 'user_details'
        | 'user_index'
      views: 'default' | 'logs'
    }
    'src/pages/home/(admin)/role/index.vue': {
      routes: 'role'
      views: never
    }
    'src/pages/home/(admin)/user/index.vue': {
      routes: 'user'
      views: never
    }
    'src/pages/home/(admin)/user/create.[[id]].vue': {
      routes: 'user_create'
      views: never
    }
    'src/pages/home/(admin)/user/details.[id].vue': {
      routes: 'user_details'
      views: never
    }
    'src/pages/home/index.vue': {
      routes: '/home/'
      views: never
    }
    'src/pages/home/index@logs.vue': {
      routes: '/home/'
      views: never
    }
    'src/pages/home/dashboard.vue': {
      routes: '/home/dashboard' | '/home/dashboard/'
      views: 'default' | 'logs'
    }
    'src/pages/home/dashboard/index.vue': {
      routes: '/home/dashboard/'
      views: never
    }
    'src/pages/home/dashboard/index@logs.vue': {
      routes: '/home/dashboard/'
      views: never
    }
    'src/pages/home/role.vue': {
      routes: 'role_index'
      views: never
    }
    'src/pages/home/task.vue': {
      routes: 'task' | 'task_index'
      views: 'default'
    }
    'src/pages/home/task/index.vue': {
      routes: 'task_index'
      views: never
    }
    'src/pages/home/user.vue': {
      routes: 'user_index'
      views: never
    }
    'src/pages/login.vue': {
      routes: 'login'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info> ? Info['routes'] : keyof RouteNamedMap
}

export {}
